server:
  port: 6325

spring:
  elasticsearch:
    jest:
      uris:
      - http://localhost:9200
      - http://localhost:9201  # ES服务器的地址！
      read-timeout: 5000
      multi-threaded: true
      connection-timeout: 5000