server:
  port: 6325

spring:
  elasticsearch:
    jest:
      uris:
      - http://192.168.0.196:9200
      - http://192.168.0.196:9200  # ES服务器的地址！
      read-timeout: 5000
      multi-threaded: true
      connection-timeout: 5000